before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:    
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    id: "ubw"
    binary: "img2"
    goos:
      - linux
      - windows
      - darwin